INSERT INTO MOVIE (ID, TITLE, GENRE, RELEASE_YEAR) VALUES (1, 'The Matrix', 'Science Fiction', 1999);
INSERT INTO MOVIE (ID, TITLE, GENRE, RELEASE_YEAR) VALUES (2, 'Inception', 'Thriller', 2010);
INSERT INTO MOVIE (ID, TITLE, GENRE, RELEASE_YEAR) VALUES (3, 'Interstellar', 'Science Fiction', 2014);
